name: zloop

on:
  push:
  pull_request:

jobs:
  zloop:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: echo-default-env-variables
      run: |
        echo "Home: ${HOME}"
        echo "GITHUB_WORKFLOW   - ${GITHUB_WORKFLOW}"
        echo "GITHUB_RUN_ID     - ${GITHUB_RUN_ID}"
        echo "GITHUB_RUN_NUMBER - ${GITHUB_RUN_NUMBER}"
        echo "GITHUB_ACTION     - ${GITHUB_ACTION}"
        echo "GITHUB_ACTIONS    - ${GITHUB_ACTIONS}"
        echo "GITHUB_ACTOR      - ${GITHUB_ACTOR}"
        echo "GITHUB_REPOSITORY - ${GITHUB_REPOSITORY}"
        echo "GITHUB_EVENT_NAME - ${GITHUB_EVENT_NAME}"
        echo "GITHUB_EVENT_PATH - ${GITHUB_EVENT_PATH}"
        echo "GITHUB_WORKSPACE  - ${GITHUB_WORKSPACE}"
        echo "GITHUB_SHA        - ${GITHUB_SHA}"
        echo "GITHUB_REF        - ${GITHUB_REF}"
        echo "GITHUB_HEAD_REF   - ${GITHUB_HEAD_REF}"
        echo "GITHUB_BASE_REF   - ${GITHUB_BASE_REF}"
        echo "GITHUB_SERVER_URL - ${GITHUB_SERVER_URL}"
        echo "GITHUB_API_URL    - ${GITHUB_API_URL}"
        echo "GITHUB_GRAPHQL_URL- ${GITHUB_GRAPHQL_URL}"
    - name: Generating summary
      run: ./generate-summary.sh
    - name: Generating summary...
      run: ./generate-summary.sh 1
    - name: Generating summary...
      run: ./generate-summary.sh 2
    - name: Generating summary...
      run: ./generate-summary.sh 3
    - name: Generating summary...
      run: ./generate-summary.sh 4
    - name: Generating summary...
      run: ./generate-summary.sh 5
    - name: Generating summary...
      run: ./generate-summary.sh 6
    - name: Generating summary...
      run: ./generate-summary.sh 7
    - name: Generating summary...
      run: ./generate-summary.sh 8
    - name: Generating summary...
      run: ./generate-summary.sh 9
    - name: Generating summary...
      run: ./generate-summary.sh 10
    - name: Generating summary...
      run: ./generate-summary.sh 11
    - name: Generating summary...
      run: ./generate-summary.sh 12
    - name: Generating summary...
      run: ./generate-summary.sh 13
    - name: Generating summary...
      run: ./generate-summary.sh 14
    - name: Generating summary...
      run: ./generate-summary.sh 15
    - name: Generating summary...
      run: ./generate-summary.sh 16
    - name: Generating summary...
      run: ./generate-summary.sh 17
    - name: Generating summary...
      run: ./generate-summary.sh 18
    - name: Generating summary...
      run: ./generate-summary.sh 19
    - name: Generating summary...
      run: ./generate-summary.sh 20
