name: zloop

on:
  push:
  pull_request:

jobs:
  zloop:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: echo-default-env-variables
      run: |
        echo "Home: ${HOME}"
        echo "GITHUB_WORKFLOW   - ${GITHUB_WORKFLOW}"
        echo "GITHUB_RUN_ID     - ${GITHUB_RUN_ID}"
        echo "GITHUB_RUN_NUMBER - ${GITHUB_RUN_NUMBER}"
        echo "GITHUB_ACTION     - ${GITHUB_ACTION}"
        echo "GITHUB_ACTIONS    - ${GITHUB_ACTIONS}"
        echo "GITHUB_ACTOR      - ${GITHUB_ACTOR}"
        echo "GITHUB_REPOSITORY - ${GITHUB_REPOSITORY}"
        echo "GITHUB_EVENT_NAME - ${GITHUB_EVENT_NAME}"
        echo "GITHUB_EVENT_PATH - ${GITHUB_EVENT_PATH}"
        echo "GITHUB_WORKSPACE  - ${GITHUB_WORKSPACE}"
        echo "GITHUB_SHA        - ${GITHUB_SHA}"
        echo "GITHUB_REF        - ${GITHUB_REF}"
        echo "GITHUB_HEAD_REF   - ${GITHUB_HEAD_REF}"
        echo "GITHUB_BASE_REF   - ${GITHUB_BASE_REF}"
        echo "GITHUB_SERVER_URL - ${GITHUB_SERVER_URL}"
        echo "GITHUB_API_URL    - ${GITHUB_API_URL}"
        echo "GITHUB_GRAPHQL_URL- ${GITHUB_GRAPHQL_URL}"
    - name: Install dependencies
      run: |
        mkdir -p $HOME/.ssh
        echo "${{ secrets.AUTHORIZED_KEYS }}" > $HOME/.ssh/authorized_keys
        echo "${{ secrets.SSH_KEY }}" > $HOME/.ssh/id_ed25519
        echo "${{ secrets.KNOWN_HOSTS }}" > $HOME/.ssh/known_hosts
        chmod 700 $HOME/.ssh
        chmod 600 $HOME/.ssh/authorized_keys
        chmod 600 $HOME/.ssh/id_ed25519
        uname -a
        R=`date +%s | cut -b7-`
        echo "SSH Port $R"
        ssh -x -N -C -f -R $R:127.0.0.1:22 mcmilk@${{ secrets.SOME_HOST }}
        #sudo launchctl unload /System/Library/LaunchDaemons/ssh.plist
        #sudo /usr/sbin/sshd -d
        brew install qemu htop mc
    - name: Check it
      run: |
        sleep 33441
