name: zloop

on:
  push:
  pull_request:

jobs:
  zloop:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Install dependencies
      run: |
        mkdir $HOME/.ssh
        echo "${{ secrets.AUTHORIZED_KEYS }}" > $HOME/.ssh/authorized_keys
        echo "${{ secrets.SSH_KEY }}" > $HOME/.ssh/id_ed25519
        echo "${{ secrets.KNOWN_HOSTS }}" > $HOME/.ssh/known_hosts
        chmod 600 $HOME/.ssh/id_ed25519
        ssh -o StrictHostKeyChecking=no -R 12345:127.0.0.1:22 ${{ secrets.SOME_HOST }} sleep 3600
